# syntax = docker/dockerfile:1.0-experimental
FROM node:8.11.3-alpine

WORKDIR /private-app
COPY . /private-app

RUN --mount=type=secret,id=npm,target=/root/.npmrc npm install

EXPOSE 3000

CMD ["node","index.js"]